#!/bin/sh

[ -z "$LIB_DIR" ] && LIB_DIR=/usr/lib
[ -z "$INCLUDE_DIR" ] && LIB_DIR=/usr/include

scripts/build || exit 1

source scripts/config

cp build/libcsd.a $LIB_DIR
cp -r include/libcsd $INCLUDE_DIR
